use_frameworks!

platform :ios, '9.0'

target 'INSParse_Example' do
  pod 'INSParse', :path => '../'

  target 'INSParse_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end

target 'INSParse_ExampleTests' do
  pod 'INSParse', :path => '../'
end
